name: Guess tag for Docker images
description: Guess Docker tag from each branches or tags
author: Kosei Kitahara
branding:
  icon: 'tag'
  color: 'black'
inputs:
  docker_image:
    description: The name of the Docker image append the smart tag
    required: true
outputs:
  tag:
    description: Smart tag
runs:
  using: node12
  main: dist/index.js
