name: Docker GitOps Tag Action
description: Generate GitOps friendly sortable Docker image tags
author: Andrew Lees
branding:
  icon: 'git-branch'
  color: 'blue'
inputs:
  docker_image:
    description: The name of the Docker image prepend the generated tag
    required: true
outputs:
  tag:
    description: Tagged image.
runs:
  using: node12
  main: dist/index.js
